###### 3장 템플릿
# 3.1. 다시 보는 초난감 DAO

**템플릿**이란 성질이 다른 코드 중에서 변경이 거의 일어나지 않으며 일정한 패턴으로 유지되는 특성을 가진 부분을 자유롭게 변경되는 성질을 가진 부분으로부터 독립시켜서 효과적으로 활용할 수 있도록 하는 방법이다. 
3장에서는 스프링에 적용된 템플릿 기법을 살펴보고, 이를 적용해 완성도 있는 DAO 코드를 만드는 방법을 알아보겠다.   

<br/>

### 예외처리 기능을 갖춘 DAO 

`UserDao`의 코드에는 아직 문제점이 남아 있다. DB 연결과 관련된 여러 가지 개선 작업은 했지만, 다른 면에서 심각한 문제점이 있다. 바로 예외상황에 대한 처리다. 
`UserDao`의 가장 단순한 메소드인 `deleteAll()`을 살펴보자.         

```java
public void deleteAll() throws SQLException {
    Connection c = dataSource.getConnection();
  
    PreparedStatement ps = c.prepareStatement("delete from users");
    ps.executeUpdate();
    
    ps.close();
    c.close();
}
```

이 메소드에서는 `Connection`과 `PreparedStatement`라는 두 개의 공유 리소스를 가져와서 사용한다. 물론 정상적으로 처리되면 메소드를 마치기 전에 각각 `close()`를 호출해 
리소스를 반환한다. 그런데 `PreparedStatement`를 처리하는 중에 예외가 발생하면 어떻게 될까? 이때는 메소드 실행을 끝마치지 못하고 바로 메소드를 빠져나가게 된다. 
이 때 문제는 `Connection`과 `PreparedStatement`의 `close()` 메소드가 실행되지 않아서 제대로 리소스가 반환되지 않을 수 있다는 점이다.             

일반적으로 서버에서는 제한된 개수의 DB 커넥션을 만들어서 재사용 가능한 풀로 관리한다. DB 풀은 매번 `getConnection()`으로 가져간 커넥션을 명시적으로 `close()`해서 돌려줘야지만 
다시 풀에 넣었다가 다음 커넥션 요청이 있을 때 재사용할 수 있다. 그런데 이런 식으로 오류가 날 때마다 미처 반환되지 못한 `Connection`이 계속 쌓이면 어느 순간에 커넥션 풀에 여유가 없어지고 
리소스가 모자란다는 심각한 오류를 내며 서버가 중단될 수 있다. 따라서 위의 코드는 한 번 실행되고 애플리케이션 전체가 종료되는 간단한 예제에서는 괜찮겠지만, 장시간 운영되는 다중 사용자를 위한 
서버에 적용하기에는 치명적인 위험을 내포하고 있다.         

그래서 이런 JDBC 코드에서는 **어떤 상황에서도 가져온 리소스를 반환**하도록 `try`/`catch`/`finally` 구문 사용을 권장하고 있다.      
```java
public void deleteAll() throws SQLException {
    Connection c = null;
    PreparedStatement ps = null;
  
    try {
        c = dataSource.getConnection();
        ps = c.prepareStatement("delete from users");
        ps.executeUpdate();
    } catch (SQLException e) {
        throw e;
    } finally {
        if (ps != null) {
            try {
                ps.close();
            } catch (SQLException e) {
            }
        }
        if (c != null) {
            try {
                c.close();
            } catch (SQLException e) {
            }
        }
    }
}
```
> 예외 발생 시에도 리소스를 반환하도록 수정한 deleteAll()

예외가 어느 시점에 나는가에 따라서 `Cnnection`과 `PreparedStatement` 중 어떤 것의 `close()` 메소드를 호출해야 할지가 달라지므로, `finally`에서는 반드시 
`c`와 `ps`가 `null`이 아닌지 먼저 확인한 후에 `close()` 메소드를 호출해야 한다.              

문제는 이 `close()`도 `SQLException`이 발생할 수 있는 메소드라는 점이다. 따라서 `try`/`catch` 문으로 처리해줘야 한다. 물론 `close()`가 실패했을 때는 특별히 
해줄 수 있는 조치가 없기 때문에 `catch` 블록은 비어 있다. 이미 `deleteAll`에 `SQLException`이 던져진다고 선언되어 있으니 `close()`에는 `try`/`catch`가 없어도 되지 않을까 
생각할 수도 있다. 하지만 반드시 있어야 한다. `try`/`catch` 없이 `ps.close()`를 처리하다가 예외가 발생하면 아래 `c.close()` 부분이 실행되지 않고 메소드를 빠져나가는 문제가 발생하기 때문이다. 

<br/>

### JDBC 조회 기능의 예외처리 

조회를 위한 JDBC 코드는 좀 더 복잡해진다. `Connection`, `PreparedStatement` 외에도 `ResultSet`이 추가되기 때문이다. 등록된 `User`의 수를 가져오는 `getCount()` 메소드에 
예외처리 블록을 적용해보면 리스트 3-3과 같은 코드가 만들어진다.      

```java
public int getCount() throws SQLException {
    Connection c = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
  
    try {
        c = dataSource.getConnection();
      
        ps = c.prepareStatement("select count(*) from users");
      
        rs = ps.executeQuery();
        rs.next();
        return rs.getInt(1);
    } catch (SQLException e) {
        throw e;
    } finally {
        /* close()는 만들어진 순서의 반대로 하는 것이 원칙이다. */
        if (rs != null) { 
            try {
            } catch (SQLException e) {
            }
        }
        if (ps != null) {
            try {
                ps.close();
            } catch (SQLException e) {
            }
        }
        if (c != null) {
            try {
                c.close();
            } catch (SQLException e) {
            }
        }
    }
}
```

-----

**다음 글 - [*3.2. 변하는 것과 변하지 않는 것*](./3.2.%20변하는%20것과%20변하지%20않는%20것.md)**
